###
GET http://localhost:5000/

###
POST http://localhost:5000/api/post
Content-Type: application/json

{
    "user_id": 105,
    "text": "testtesttest"
}

###
GET http://localhost:5000/api/post

###
PUT http://localhost:5000/api/post
Content-Type: application/json

{
    "user_id": 105,
    "post_id": 276,
    "text": "chinponya!!!"
}

###
DELETE http://localhost:5000/api/post
Content-Type: application/json

{
    "post_id": 276
}

###
POST http://localhost:5000/api/register
Content-Type: application/json

{
    "email": "hoge@fuga.com",
    "name": "tester",
    "password": "hogenhogen"
}
