###
GET http://localhost:5000/

###
POST http://localhost:5000/api/post
Content-Type: application/json
Authorization: 'eyJhbGciOiJIUzI1NiJ9.aG9nZUBmdWdhLmNvbQ.S4V6rKlzA2s31-hsKPke3GjnK5bSssVLc72P604Abv8'

{
    "user_id": 1,
    "text": "testtesttest"
}

###
GET http://localhost:5000/api/post

###
PUT http://localhost:5000/api/post
Content-Type: application/json

{
    "user_id": 105,
    "post_id": 348,
    "text": "chinponya!!!"
}

###
DELETE http://localhost:5000/api/post
Content-Type: application/json

{
    "post_id": 276
}

###
POST http://localhost:5000/api/register
Content-Type: application/json

{
    "email": "hoge@fuga.com",
    "name": "tester",
    "password": "hogenhogen"
}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "hoge@fuga.com",
    "password": "hogenhogen"
}

###
GET http://localhost:5000/api/validate/105

